### ISSUE TITLE
Desktop layout

### ISSUE THREAD

**Issue by JMoneymaker** [plot-a-pi/pi#137]

**Comment by licarpen** [comment]
I've been working on this in bits and pieces - the header/nav are now responsive.  Still working out a layout that will work with the new, responsive graphs.

**Comment by licarpen** [comment]
Home, MonteCarlo, and DataEntryForm are now responsive in that they look ok on desktop.  Next step is to change layout instead of keeping it in a vertical column for larger screen sizes.
